name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "d35c3f80-0da1-4ea4-927d-021660f229d7"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "8634b457b99f434da2a9caba40f3c08c"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
