name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "73d2e102-981b-4d81-9fb7-2752bfa425fe"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "2791dd2fbfc443978743f1633c526548"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
