name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "777333bd-baf0-4a17-90a4-be34ccf9db37"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "cda45c6914c94bc8904dbb55b2fc92d9"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
